package entity;
// Generated 30.03.2018 11:03:23 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Gruppyi generated by hbm2java
 */
@Entity
@Table(name="gruppyi"
    ,catalog="dek"
    , uniqueConstraints = @UniqueConstraint(columnNames="Nazvanie") 
)
public class Gruppyi  implements java.io.Serializable {


     private Integer shifr;
     private Uchebnyieplanyi uchebnyieplanyi;
     private String nazvanie;
     private Date dataFormir;
     private String status;
     private Date statusDate;

    public Gruppyi() {
    }

	
    public Gruppyi(Uchebnyieplanyi uchebnyieplanyi, String nazvanie, Date dataFormir) {
        this.uchebnyieplanyi = uchebnyieplanyi;
        this.nazvanie = nazvanie;
        this.dataFormir = dataFormir;
    }
    public Gruppyi(Uchebnyieplanyi uchebnyieplanyi, String nazvanie, Date dataFormir, String status, Date statusDate) {
       this.uchebnyieplanyi = uchebnyieplanyi;
       this.nazvanie = nazvanie;
       this.dataFormir = dataFormir;
       this.status = status;
       this.statusDate = statusDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Shifr", unique=true, nullable=false)
    public Integer getShifr() {
        return this.shifr;
    }
    
    public void setShifr(Integer shifr) {
        this.shifr = shifr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="KodPlana", nullable=false)
    public Uchebnyieplanyi getUchebnyieplanyi() {
        return this.uchebnyieplanyi;
    }
    
    public void setUchebnyieplanyi(Uchebnyieplanyi uchebnyieplanyi) {
        this.uchebnyieplanyi = uchebnyieplanyi;
    }

    
    @Column(name="Nazvanie", unique=true, nullable=false, length=50)
    public String getNazvanie() {
        return this.nazvanie;
    }
    
    public void setNazvanie(String nazvanie) {
        this.nazvanie = nazvanie;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DataFormir", nullable=false, length=10)
    public Date getDataFormir() {
        return this.dataFormir;
    }
    
    public void setDataFormir(Date dataFormir) {
        this.dataFormir = dataFormir;
    }

    
    @Column(name="Status", length=50)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="StatusDate", length=10)
    public Date getStatusDate() {
        return this.statusDate;
    }
    
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }




}


