package entity;
// Generated 30.03.2018 11:03:23 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Uchebnyieplanyi generated by hbm2java
 */
@Entity
@Table(name="uchebnyieplanyi"
    ,catalog="dek"
    , uniqueConstraints = @UniqueConstraint(columnNames="NomerPlana") 
)
public class Uchebnyieplanyi  implements java.io.Serializable {


     private Integer kodPlana;
     private Spetsialnosti spetsialnosti;
     private String nomerPlana;
     private Date dataUtv;
     private String nomer;
     private String status;
     private Date statusDate;
     private List<Gruppyi> gruppyis;

    public Uchebnyieplanyi() {
    }

	
    public Uchebnyieplanyi(Spetsialnosti spetsialnosti, String nomerPlana, Date dataUtv, String nomer) {
        this.spetsialnosti = spetsialnosti;
        this.nomerPlana = nomerPlana;
        this.dataUtv = dataUtv;
        this.nomer = nomer;
    }
    public Uchebnyieplanyi(Spetsialnosti spetsialnosti, String nomerPlana, Date dataUtv, String nomer, String status, Date statusDate, List<Gruppyi> gruppyis) {
       this.spetsialnosti = spetsialnosti;
       this.nomerPlana = nomerPlana;
       this.dataUtv = dataUtv;
       this.nomer = nomer;
       this.status = status;
       this.statusDate = statusDate;
       this.gruppyis = gruppyis;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="KodPlana", unique=true, nullable=false)
    public Integer getKodPlana() {
        return this.kodPlana;
    }
    
    public void setKodPlana(Integer kodPlana) {
        this.kodPlana = kodPlana;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="KodSpets", nullable=false)
    public Spetsialnosti getSpetsialnosti() {
        return this.spetsialnosti;
    }
    
    public void setSpetsialnosti(Spetsialnosti spetsialnosti) {
        this.spetsialnosti = spetsialnosti;
    }

    
    @Column(name="NomerPlana", unique=true, nullable=false, length=10)
    public String getNomerPlana() {
        return this.nomerPlana;
    }
    
    public void setNomerPlana(String nomerPlana) {
        this.nomerPlana = nomerPlana;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DataUtv", nullable=false, length=10)
    public Date getDataUtv() {
        return this.dataUtv;
    }
    
    public void setDataUtv(Date dataUtv) {
        this.dataUtv = dataUtv;
    }

    
    @Column(name="Nomer", nullable=false, length=10)
    public String getNomer() {
        return this.nomer;
    }
    
    public void setNomer(String nomer) {
        this.nomer = nomer;
    }

    
    @Column(name="Status", length=50)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="StatusDate", length=10)
    public Date getStatusDate() {
        return this.statusDate;
    }
    
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="uchebnyieplanyi")
    public List<Gruppyi> getGruppyis() {
        return this.gruppyis;
    }
    
    public void setGruppyis(List<Gruppyi> gruppyis) {
        this.gruppyis = gruppyis;
    }




}


